// <auto-generated />
namespace EasyGeneratorAdditionalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Db201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Db201));
        
        string IMigrationMetadata.Id
        {
            get { return "201607092011591_Db 2.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
