// <auto-generated />
namespace EasyGeneratorAdditionalProject.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class normalsingleselectimageanswerobject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(normalsingleselectimageanswerobject));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111037376_normal single select image answer object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
